export const Config = {
  SEC_ANIMATION__DELAY: 1000,
  INIT_ALGO_NAME: "Insertion",
  INIT_ARR_SIZE: 15,
  RAND_ARR_LOW_VAL: 4,
  RAND_ARR_MAX_VAL: 30,
  INPUT_RANGE_MIN: 5,
  INPUT_RANGE_MAX: 15,
};
